version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  publish_wap: true
  verbosity: normal
notifications:
- provider: Email
  to:
  - alvahdean@gmail.com
  subject: Appveyor Notification
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true